#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba16f, binding = 0) uniform image2D imgIn;
layout(rgba16f, binding = 1) uniform image2D imgOut;

//This reads the texture in, and outputs to the texture out.
void main(){
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec4 invalue = imageLoad(imgIn,texelCoord);

    vec4 outval = vec4(1,0,0,1);
    imageStore(imgOut, texelCoord, outval);
}