#version 310 es

/*
    THE ANDROID HALF OF THE BLAST. The desktop half is shaders/bomber_explosion.frag and the two
    are a deliberate, permanent pair - see the block at the top of that file for the effect this
    one is a reduction of, and ApplicationBomber::BuildExplosion for how one of the two is chosen.

    --- WHY A SECOND FILE AND NOT AN #ifdef -----------------------------------------------------
    bomber_explosion.frag cannot be made to run here, and not for one reason that could be patched
    out. Measured on the MDT740 (GLES 3.1, Mali):

      - It is `#version 430 core`. There is no desktop GLSL on this device at any version.
      - It reads its instance transform and the scene's lights from SSBOs. This device reports
        GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0 - not a small number, ZERO - so an SSBO in the
        fragment stage is a link error here, not a slow path. The same instance data is already in
        a std140 UBO at binding 2 for default_android.vert, which is what this file reads.
      - Every uniform in it carries a default initialiser (`uniform float heat = 0.90;`). GLSL ES
        forbids those outright.
      - It samples a sampler3D of Worley noise generated by shaders/noise3d.comp. There are no
        compute shaders in the GLES 3.1 core profile this device exposes for that path, and the
        texture is bound with glBindTextureUnit, which is DSA and absent at every GLES version.

    Four independent blockers, three of them structural. So this is a reduction, not a port.

    --- WHAT IS THE SAME, AND THAT IS THE POINT -------------------------------------------------
    THE SHAPE LOGIC IS SHARED, THE SHADING IS NOT. setup_instance() below is the desktop file's
    TILE-mode branch, arithmetic for arithmetic: the same ring-from-the-bomb, the same arm_limit
    test against what the maze allows, the same `local_age = blast_age - ring * tile_delay` stagger
    and the same expansion() curve. So WHICH tiles light and WHEN is identical on both platforms
    and stays identical when a knob moves - only what a lit tile looks like differs.

    That split is chosen rather than incidental. A difference in the timing or the reach would be
    a difference in the GAME; a difference in the shading is a difference in the picture. The
    second is a fair price for a device that cannot march a volume, the first would not be.

    --- WHAT IS LOST ----------------------------------------------------------------------------
      - The march. This is ONE analytic ray/sphere intersection, no loop, no texture fetch. The
        shape is a smooth ball rather than a noise-displaced burning shell.
      - BLAST_MODE_CROSS. The cross is one big box whose density is a distance field around a
        four-armed skeleton, which only means anything to a march. The app does not ask for it
        here (f_draw_cross is false by default in ApplicationBomber), and this file discards rather
        than drawing a single fat ball where a cross was meant - a wrong shape is worse than none.
      - Smoke lit by the scene's lights, which needed the light SSBO.

    Cost baseline for the analytic form on this device is in docs/custom-shader-pass-gles-port.md;
    this file is the shader that measurement was taken with, moved from bomber_test_port and given
    apps/bomber's uniform names so that ApplicationBomber::PushBlastUniforms is ONE function with
    one guarded block rather than two.
*/

//highp explicitly: this reconstructs a world-space ray and intersects it with a sphere, so the
//positions are world coordinates rather than 0..1 quantities. mediump on a Mali is 10 bits of
//mantissa and would make the sphere visibly faceted and jitter as the camera moves.
precision highp float;

//From default_android.vert, unchanged - this shader is linked against it like any other custom
//shader. The desktop file reads the same two things under the names vposition and vmatselect.
in vec3 vposition;          //world-space position of the box surface this fragment is on
flat in int vinstanceid;    //= gl_InstanceID, our index into instance_data

#define MAX_INSTANCES 128   // == RENDERER_MAX_INSTANCES
struct InstanceData{
    mat4 mat_transformscale;
    ivec4 material_slot;
    ivec4 objectid_data;
    vec4 uv_transform;
};
layout (std140, binding = 2) uniform InstanceDataBlock{
    InstanceData instance_data[MAX_INSTANCES];
};

//Must match the BLAST_MODE_* enum in ApplicationBomber.cpp and in the desktop shader.
#define BLAST_MODE_TILE   0
#define BLAST_MODE_CROSS  1

//Set by Renderer::CustomShaderPass for every custom shader - a volume is intersected from the eye
//and cannot recover the camera position from the matrices without inverting one. The desktop file
//calls this eye_position; the name here is the one CustomShaderPass already sets in this tree.
uniform vec3 uCameraPos;

/*
    --- THE SHARED UNIFORMS ---------------------------------------------------------------------
    Every name below is apps/bomber's, pushed by the unguarded half of PushBlastUniforms, and
    means exactly what it means in bomber_explosion.frag. NO DEFAULT INITIALISERS - GLSL ES has no
    such thing, so each one is set from C++ before the first draw or it is zero.
*/
uniform int   blast_mode;
uniform float blast_age;        //SIMULATION TICKS since detonation. Negative = nothing burning.
uniform float blast_life;       //Ticks a tile burns for
uniform float blast_seed;       //Per-blast variation, so two blasts are not the same blast
uniform vec4  arm_limit;        //Tiles the maze allows: x=+X, y=-X, z=-Z, w=+Z
uniform vec3  blast_origin;     //World position of the bomb
uniform float cell_world;       //World size of one maze cell
uniform float tile_delay;       //Ticks a ring waits for the one inside it
uniform float blast_radius;     //Radius the flame front reaches, in OBJECT units
uniform float rise;             //How far the flame floats up over a life, in OBJECT units
uniform int   f_show_box;       //Debug: draw the box the volume lives in

out vec4 fragColor;

//This instance's normalised age, 0 at its own detonation and 1 at its end. Written by
//setup_instance, read by everything after it - the desktop file calls it g_t for the same reason.
float g_t = 0.0;

//The growth curve, character for character from bomber_explosion.frag. Shared so a tile reaches
//the same size at the same tick on both platforms.
float expansion(float t){
    return 1.0 - pow(1.0 - t,5.0);
}

/*
    Which tile of the cross this instance is, whether the maze lets it burn, and how far through
    its own life it is.

    THE DESKTOP FILE'S TILE BRANCH, unchanged. Read setup_instance there for why the ring is
    rounded, why the centre tile needs no special case, and why a blocked arm simply has no lit
    tiles past the wall.
*/
bool setup_instance(mat4 transform){
    if (blast_mode == BLAST_MODE_CROSS){
        //Not drawn here - see WHAT IS LOST above. Discarding is the honest answer: a ball in the
        //bounding box of a cross is a different effect, not a cheaper one.
        return false;
    }

    vec3 offset = transform[3].xyz - blast_origin;
    float cells_x = offset.x / max(cell_world,0.0001);
    float cells_z = offset.z / max(cell_world,0.0001);
    //Which ring out from the bomb. Rounded, because a tile's centre is on its cell and the
    //arithmetic only has to survive float error, not arbitrary placement.
    float ring = max(abs(cells_x),abs(cells_z));
    ring = floor(ring + 0.5);

    //Which arm, and therefore which limit applies. The centre tile (ring 0) is always lit, and
    //falls out of this without a special case: every limit is at least 0.
    float limit = arm_limit.x;                                  //east, +X
    if (abs(cells_x) > abs(cells_z)){
        limit = (cells_x > 0.0) ? arm_limit.x : arm_limit.y;    //east / west
    }else if (abs(cells_z) > abs(cells_x)){
        limit = (cells_z < 0.0) ? arm_limit.z : arm_limit.w;    //north (-Z) / south (+Z)
    }
    if (ring > limit + 0.5){
        return false;   //the maze stops the flame before this tile
    }

    //Each ring waits for the one inside it. A tile that has not caught yet, or has burnt out,
    //draws nothing - so the tiles of one blast are at different points of the same curve, which
    //is exactly the staggered flame the original game has.
    float local_age = blast_age - ring * tile_delay;
    if (local_age < 0.0 || local_age > blast_life){
        return false;
    }
    g_t = clamp(local_age / max(blast_life,1.0),0.0,1.0);
    return true;
}

void main(){
    mat4 transform = instance_data[vinstanceid].mat_transformscale;

    //Nothing is burning here. Cheapest possible exit, taken on every pixel of every box for most
    //of the app's life - the objects stay in the scene rather than being hidden, so that a
    //detonation is one uniform changing and never a visibility flag racing the render thread.
    if (!setup_instance(transform)){
        discard;
    }

    /*
        OBJECT UNITS TO WORLD UNITS, through the instance's own scale.

        blast_radius and rise are fractions of the box (see the desktop file's UNITS section), and
        the box is Primitives::MakeBox's unit cube spanning -0.5..+0.5, so column 0 of the
        transform has length equal to the box's world size. Reading it from the matrix rather than
        taking it as a uniform is what lets several tiles batch into ONE draw call, which is the
        whole reason the instance data is per instance.
    */
    float box_world = length(transform[0].xyz);
    vec3  centre    = transform[3].xyz;

    //The same front radius and the same quadratic float-up as the desktop march's, so a tile is
    //the same size in the same place - only its interior is cheaper.
    float radius = max(blast_radius * expansion(g_t),0.02) * box_world;
    centre.y += rise * g_t * g_t * box_world;
    if (radius <= 0.0){
        discard;
    }

    //The eye ray, reconstructed from the box surface this fragment sits on. Only the pixels the
    //box covers ever get here, which is the whole trick behind drawing a volume as a mesh. We are
    //rasterising BACK faces, but the analytic intersection does not care which face it was handed
    //and works identically with the camera outside or inside the volume.
    vec3 ray_origin = uCameraPos;
    vec3 ray_dir = normalize(vposition - ray_origin);

    //Analytic ray/sphere. b and c are the usual quadratic terms with the ray direction normalised,
    //so the discriminant is b*b - c and there is no 2a to divide by.
    vec3 to_centre = ray_origin - centre;
    float b = dot(to_centre,ray_dir);
    float c = dot(to_centre,to_centre) - (radius * radius);
    float h = (b * b) - c;
    if (h < 0.0){
        //The box covers this pixel but the sphere inside it does not. This is the corner of the
        //box, and discarding is what makes the volume round rather than cubic.
        if (f_show_box != 0){
            fragColor = vec4(0.0,0.25,0.0,0.25);
            return;
        }
        discard;
    }
    h = sqrt(h);
    float t_near = -b - h;
    float t_far  = -b + h;
    if (t_far < 0.0){
        discard;      //entirely behind the eye
    }
    //Clamped so that standing INSIDE the fireball still shades the part in front of the eye,
    //rather than folding the chord inside out and going transparent.
    t_near = max(t_near,0.0);

    /*
        The chord through the sphere, normalised by its diameter: 1 through the dead centre, 0 at
        the silhouette. This is the only shape term in the file, and everything below is a ramp on
        it - which is what keeps the cost down to a handful of instructions.
    */
    float chord = (t_far - t_near) / (2.0 * radius);

    //--- the ramp ---------------------------------------------------------------------------
    //Hot in the middle and early, cooling outwards and with age. The seed shifts the cooling a
    //little either way so two blasts on screen together are not the same blast twice.
    float seed_bias = fract(blast_seed * 0.6180339887) * 0.12 - 0.06;
    float heat_t = clamp(chord * (1.0 - (g_t * (0.85 + seed_bias))),0.0,1.0);

    const vec3 COLOR_RED    = vec3(0.90,0.09,0.02);
    const vec3 COLOR_YELLOW = vec3(1.00,0.86,0.36);
    const vec3 COLOR_GREY   = vec3(0.30,0.29,0.28);

    vec3 fire = mix(COLOR_RED,COLOR_YELLOW,smoothstep(0.30,0.90,heat_t));
    //Late in its life the whole thing goes to smoke, rim and core together.
    vec3 color = mix(fire,COLOR_GREY,smoothstep(0.50,1.00,g_t));

    /*
        Coverage from the same chord, so the silhouette fades instead of ending on a hard circle -
        the one thing that would give away that this is a sphere and not a fireball. Faded out
        again at the very end of the life so a blast does not vanish on a frame boundary.
    */
    float alpha = clamp(chord * 1.7,0.0,1.0) * (1.0 - smoothstep(0.78,1.00,g_t));

    fragColor = vec4(color,alpha);
}
