#include "Texture.h"
#include "Debug.h"
#include "File.h"

#include "stb_image/stb_image.h"

static Debugger *debug = new Debugger("Texture", DEBUG_ALL);

Texture::Texture(){

}

Texture::~Texture(){
    if (img_data){
        free(img_data);
    }
    /*
        Release the GL object too.

        OUTSIDE the img_data test above, which is where it used to be by accident - one brace too
        far down. A Texture loaded with TEXTURE_DONT_UPLOAD, or an HDR one (whose pixels are in
        hdr_data, not img_data), therefore never released its GL name at all: the one case where
        the leak was guaranteed was the case the guard excluded.

        It never mattered while every texture lived for the whole process, which was true of every
        material and UI texture here. It starts mattering the moment something creates and destroys
        Textures repeatedly - a folder browser reloading previews, say - where skipping this leaks
        one GPU texture per reload.
    */
    Unload();
    //file_data is NOT ours to free - LoadFile lends it out and the file layer keeps it for the
    //life of the process (see File.h). img_data next to it IS ours: stb decoded that for us.
    file_data = NULL;
    file_data_sz = 0;
    if (hdr_data){
        stbi_image_free(hdr_data);
    }
}

//See the declaration in Texture.h. -1 is the sentinel, not 0: glGenTextures never hands out 0,
//but this class default-initialises texture_id to -1, so that is what "never created" means.
void Texture::Unload(){
    if (texture_id != (GLuint)-1){
        glDeleteTextures(1, &texture_id);
        texture_id = (GLuint)-1;
    }
    //Regenerated by the next upload if this build uses bindless handles at all; GLES has none.
    texture_handle = 0;
}

//Creates the image handle in OpenGL
void Texture::Create2D(int target, int depth){
    if ((storage_format != GL_RGB8) && (storage_format != GL_RGBA8)){
        debug->Err("Specify GL_RGB8 or GL_RGBA8 as Create2D image format.\n");
        return;
    }

    gl_target = target;     //remembered for ReUploadTexture

    /*
        WHATEVER WAS HERE BEFORE GOES NOW. Without this, a second Create2D on the same Texture
        generates a fresh name and abandons the old allocation - the GPU keeps it, nothing points
        at it, and nothing reports it.

        Found on the Android port, where a re-upload pass walked two texture lists and re-created
        anything that was on both: apps/bomber created its splash and menu backgrounds three times
        apiece at launch, and its four 2048x2048 atlases twice, orphaning about 60 MiB before the
        title screen had drawn. Any caller that creates twice hits the same thing, which is why
        the guard belongs here rather than at that one call site.

        A no-op for a texture that has never been uploaded, and a no-op for one whose context has
        been declared lost - see Unload's declaration for why the second case matters.
    */
    Unload();

#if defined(__ANDROID__)
    /*
        GLES has no Direct State Access, so the texture has to be BOUND before it can be
        configured - the same translation core/Mesh.cpp makes for buffers and VAOs.

        PIN UNIT 0 FIRST. glActiveTexture/glBindTexture are global state, so without this the
        texture lands on whatever unit some unrelated earlier call happened to leave active, and
        every texture created here overwrites the last one on that unit. The Android port hit
        exactly this: its shadow-map setup left its own unit active, every material texture
        loaded afterwards bound to that unit in turn, and the shadow map ended up sampling a
        random material's colours - which looks like a shadow bug and is not one. Unit 0 is a
        safe scratch choice because Renderer::UploadMaterials rebinds every real unit afterwards.

        The desktop arm cannot have this bug: glTextureParameteri addresses the texture by name
        and touches no binding at all. That asymmetry is the reason DSA exists.
    */
    glGenTextures(1, &texture_id);
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(target, texture_id);
    debug->Info("Create2D: %s texture_id: %u\n",name.c_str(),texture_id);

    glTexParameteri(target, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(target, GL_TEXTURE_MIN_FILTER, GL_NEAREST_MIPMAP_NEAREST);
    glTexParameteri(target, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTexParameteri(target, GL_TEXTURE_WRAP_T, GL_REPEAT);

    //Allocates storage in GPU, but no data is transferred
    glTexStorage2D(target, 1, storage_format, width, height);
#else
    glCreateTextures(target, 1, &texture_id);
    debug->Info("Create2D: %s texture_id: %u\n",name.c_str(),texture_id);

    glTextureParameteri(texture_id, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTextureParameteri(texture_id, GL_TEXTURE_MIN_FILTER, GL_NEAREST_MIPMAP_NEAREST);
    glTextureParameteri(texture_id, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTextureParameteri(texture_id, GL_TEXTURE_WRAP_T, GL_REPEAT);

    //Allocates storage in GPU, but no data is transferred
    glTextureStorage2D(texture_id, 1, storage_format, width, height);
#endif
}

//LINEAR so a volume marching through this does not see the voxel grid, and REPEAT on every axis
//so the noise can be sampled at any scale without a seam - which is the whole reason the
//generator makes it tileable.
void Texture::Create3D(int size, GLenum format){
    Create3D(size,size,size,format,GL_REPEAT,GL_LINEAR);
}

void Texture::Create3D(int w, int h, int d, GLenum format, GLenum wrap, GLenum filter){
    width = w;
    height = h;
    depth = d;
    storage_format = format;

#if defined(__ANDROID__)
    //Bind-then-call, and unit 0 pinned first - see Create2D above for why both.
    //
    //NOT TAKEN FROM THE PORT, unlike the rest of the GLES arms in this file: the port has no
    //Create3D at all, because nothing it runs uses a volume texture. So this arm is written from
    //the 2D one and has never executed. GL_TEXTURE_3D and glTexStorage3D are both core GLES 3.0,
    //so it should hold, but treat it as untested until something on a device actually samples a
    //volume.
    glGenTextures(1, &texture_id);
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_3D, texture_id);
    debug->Info("Create3D: %s %ix%ix%i texture_id: %u\n",name.c_str(),width,height,depth,texture_id);

    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, filter);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, filter);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, wrap);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, wrap);
    glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, wrap);

    glTexStorage3D(GL_TEXTURE_3D, 1, storage_format, width, height, depth);
#else
    glCreateTextures(GL_TEXTURE_3D, 1, &texture_id);
    debug->Info("Create3D: %s %ix%ix%i texture_id: %u\n",name.c_str(),width,height,depth,texture_id);

    glTextureParameteri(texture_id, GL_TEXTURE_MAG_FILTER, filter);
    glTextureParameteri(texture_id, GL_TEXTURE_MIN_FILTER, filter);
    glTextureParameteri(texture_id, GL_TEXTURE_WRAP_S, wrap);
    glTextureParameteri(texture_id, GL_TEXTURE_WRAP_T, wrap);
    glTextureParameteri(texture_id, GL_TEXTURE_WRAP_R, wrap);

    glTextureStorage3D(texture_id, 1, storage_format, width, height, depth);
#endif
}

//Uses the first cubemap file to create an image. The second one uses the main image handle.
void Texture::LoadCubeMapFile(const char* filename, int depth_in, Texture* first_map){
    if (depth_in > 0){
        if (!first_map){
            debug->Fatal("Specify a first map for loading CubeMaps\n");
        }
        texture_id = first_map->texture_id;
        LoadFromFile(filename,GL_TEXTURE_CUBE_MAP,depth_in);
    }else{
        LoadFromFile(filename,GL_TEXTURE_CUBE_MAP,depth_in);
    }
}

//Uploads entire texture. Storage should have been allocated with Create2D
void Texture::UploadTexture(GLenum _format, int target){
    /*
        ROWS ARE TIGHTLY PACKED, AND GL DOES NOT ASSUME THAT.

        GL_UNPACK_ALIGNMENT defaults to 4: GL expects every row of the image it is handed to start
        on a 4-byte boundary. stb_image hands back rows with no padding at all, so the two agree
        only when width * channels happens to be a multiple of 4 - and when they disagree, GL reads
        each row 1 to 3 bytes further along than the last, and the picture SHEARS DIAGONALLY,
        further with every row.

        That "happens to be" is why this survived so long. Every texture in the tree until now was
        a power of two, or RGBA (4 channels, always aligned), or - like the 1200-wide bomber splash
        - an RGB image whose width times three was divisible by 4 anyway. The first asset that was
        not, a 1195-wide JPEG, came out skewed, and nothing about the symptom points at the cause.

        Setting 1 says what is actually true. It is restored to the default afterwards rather than
        left, because this is global GL state and leaving it changed is how the NEXT thing to
        surprise someone gets set up; UIOverlay::InitFontTexture already does exactly this pair
        around its own upload.
    */
    glPixelStorei(GL_UNPACK_ALIGNMENT,1);
#if defined(__ANDROID__)
    if (target == GL_TEXTURE_CUBE_MAP){
        /*
            THE ONE PLACE THE TWO ARMS ARE NOT A MECHANICAL TRANSLATION.

            The DSA call addresses a cube face as a Z SLICE of the whole cubemap object -
            glTextureSubImage3D with `depth` as the z offset. GLES has no such call, and names
            the face by its own target enum instead: GL_TEXTURE_CUBE_MAP_POSITIVE_X + face,
            which matches LoadCubeMapFile's "0-6: face index" convention for `depth`.
        */
        glActiveTexture(GL_TEXTURE0);       //see Create2D
        glBindTexture(GL_TEXTURE_CUBE_MAP, texture_id);
        glTexSubImage2D(GL_TEXTURE_CUBE_MAP_POSITIVE_X + depth, 0, 0, 0, width, height, image_format, GL_UNSIGNED_BYTE, img_data);
    }else{
        glActiveTexture(GL_TEXTURE0);       //see Create2D
        glBindTexture(target, texture_id);
        glTexSubImage2D(target, 0, 0, 0, width, height, image_format, GL_UNSIGNED_BYTE, img_data);
        glGenerateMipmap(target);
    }
#else
    if (target == GL_TEXTURE_CUBE_MAP){
        glTextureSubImage3D(texture_id,0,0,0,depth,width,height,1,image_format,GL_UNSIGNED_BYTE,img_data);
    }else{
        glTextureSubImage2D(texture_id,0,0,0,width,height,image_format,GL_UNSIGNED_BYTE,img_data);
        glGenerateTextureMipmap(texture_id);
    }
#endif
    glPixelStorei(GL_UNPACK_ALIGNMENT,4);   //back to the GL default - see the note at the top
}

//Load a decoded (PNG, JPG etc. from memory.)
void Texture::LoadFromMemory(uint8_t* data, size_t length, int target, int depth_in){
    depth = depth_in;

    int w;
	int h;
	int channels;
    stbi_set_flip_vertically_on_load(false);
    img_data = stbi_load_from_memory(data,length,&w,&h,&channels,0);
    debug->Info("Loaded image file: %i x %i %i channels\n",w,h,channels);

    //TODO: Free file data. This may not be possible when it was packed in?

    //Compute image data size
    img_data_sz = channels * w * h;

    GLenum format; //Note 2 different formats are used.
    if (channels == 4){
        format = GL_RGBA8;
    }else if (channels == 3){
        format = GL_RGB8;
    }else{
        debug->Err("Unsupported number of color channels.\n");
        return;
    }
    storage_format = format;

    if (channels == 4){
        image_format = GL_RGBA;
    }else{
        image_format = GL_RGB;
    }

    width = w;
    height = h;

    //Code for loading new image or adding to a cube map
    if (depth == TEXTURE_DONT_UPLOAD){
        debug->Info("Not uploading texture.\n");
        return;
    }

    if ((target != GL_TEXTURE_CUBE_MAP) || (depth == 0)){
        Create2D(target,depth);
    }else{
        debug->Info("Re-Using Image Handle for CubeMap\n");
    }

    UploadTexture(image_format,target);

    #ifdef BINDLESS_TEXTURES
    texture_handle = glGetTextureHandleARB(texture_id);
    if (texture_handle == 0){
        debug->Fatal("Unable to get texture handle from texture ID.\n");
    }
    debug->Info("Uploading data. Texture Handle: %llu\n",texture_handle);
    glMakeTextureHandleResidentARB(texture_handle);
    #endif
}

/*
    Filename;
    Target: Specifies the texture target GL_TEXTURE_1D, GL_TEXTURE_2D, GL_TEXTURE_3D, GL_TEXTURE_1D_ARRAY, GL_TEXTURE_2D_ARRAY, GL_TEXTURE_RECTANGLE, GL_TEXTURE_CUBE_MAP, GL_TEXTURE_CUBE_MAP_ARRAY, GL_TEXTURE_BUFFER, GL_TEXTURE_2D_MULTISAMPLE or GL_TEXTURE_2D_MULTISAMPLE_ARRAY.
    Depth: -1 will not be uploaded to GPU, GL_TEXTURE_CUBE_MAP (0-6): Face index,
*/
void Texture::LoadFromFile(const char* filename, int target, int depth_in){
    if (file_data_sz > 0){
        //Dropping a borrowed pointer, not releasing anything - the file layer owns it (File.h).
        debug->Info("LoadFromFile: Overwriting existing file data\n");
    }

    file_data = NULL;
    file_data_sz = 0;
    file_data = LoadFile(filename,&file_data_sz);
    if (!file_data){
        debug->Err("Unable to load Image File %s\n",filename);
        return;
    }

    name = filename;
    LoadFromMemory(file_data,file_data_sz,target,depth_in);
}

//CPU interpolation time!
vec3 Texture::GetValueAt(float x, float y){
    x = clamp(x, 0.0f, 1.0f);
    y = clamp(y, 0.0f, 1.0f);

    int stride = (image_format == GL_RGBA) ? 4 : 3;
    int row    = (int)((float)height * y);
    int col    = (int)((float)width  * x);
    int index  = (row * width + col) * stride;

    vec3 p = vec3(img_data[index], img_data[index+1], img_data[index+2]);
    p.x = clamp(p.x, 0, 255);
    p.y = clamp(p.y, 0, 255);
    p.z = clamp(p.z, 0, 255);
    return p;
} //Returns the pixel value at 0 ... 1 interval.

bool Texture::IsEmpty(){
    return (img_data_sz == 0);
}

void Texture::ReUploadTexture(){
    if (f_is_hdr){
        debug->Warn("ReUploadTexture: HDR re-upload not implemented (name=%s)\n", name.c_str());
        return;
    }
    if (gl_target == GL_TEXTURE_CUBE_MAP){
        debug->Warn("ReUploadTexture: cubemap re-upload not implemented (name=%s)\n", name.c_str());
        return;
    }
    if (!img_data || img_data_sz == 0){
        return; // Nothing decoded (e.g. TEXTURE_DONT_UPLOAD was used), nothing to redo.
    }
    Create2D(gl_target, depth);
    UploadTexture(image_format, gl_target);
}

void Texture::InvertRGB(){
    if (!img_data || img_data_sz == 0){
        debug->Warn("InvertRGB: no decoded image data to invert\n");
        return;
    }
    int channels = (image_format == GL_RGBA) ? 4 : 3;
    size_t pixel_count = img_data_sz / channels;
    for (size_t i = 0; i < pixel_count; i++){
        uint8_t* pixel = img_data + (i * channels);
        pixel[0] = 255 - pixel[0];
        pixel[1] = 255 - pixel[1];
        pixel[2] = 255 - pixel[2];
        //pixel[3] (alpha), when channels == 4, is deliberately left alone.
    }

    UploadTexture(image_format, gl_target);
}


void Texture::CopyLine(uint8_t* line, int num_pixels, uint8_t* out, int num_color_channels){
    if (line && out)
    memcpy(out,line,num_pixels * num_color_channels);
}

// Load a Radiance HDR (.hdr) file into float CPU data.
// depth_in = TEXTURE_DONT_UPLOAD: CPU only (for cubemap conversion).
// depth_in = 0: upload as a plain GL_TEXTURE_2D.
void Texture::LoadHDRFromFile(const char* filename, int depth_in){
    f_is_hdr = true;
    name     = filename;
    depth    = depth_in;

    /*
        stbi_loadf opens the file itself, so this is one of the few places that has to resolve a
        name to a real path rather than hand it to LoadFile - see core/File.h. Without it the HDR
        is only found when the working directory happens to be the one the name is relative to,
        which stopped being true the moment each app got its own build folder.

        The name is kept as given in `name` above: that is the asset's identity, and it is what a
        second load of the same environment map should match on.
    */
    std::string resolved;
    if (!ResolveAssetPath(filename, resolved)){
        debug->Err("LoadHDRFromFile: no such file %s - looked in: %s\n", filename, resolved.c_str());
        return;
    }

    int w, h, channels;
    stbi_set_flip_vertically_on_load(false);
    hdr_data = stbi_loadf(resolved.c_str(), &w, &h, &channels, 3); // force RGB
    if (!hdr_data){
        debug->Err("LoadHDRFromFile: failed to load %s: %s\n", resolved.c_str(), stbi_failure_reason());
        return;
    }
    width       = w;
    height      = h;
    hdr_data_sz = (size_t)w * h * 3 * sizeof(float);
    storage_format = GL_RGB16F;
    image_format   = GL_RGB;
    debug->Info("LoadHDRFromFile: %s  %i x %i\n", filename, w, h);

    if (depth_in == TEXTURE_DONT_UPLOAD){
        return;
    }

#if defined(__ANDROID__)
    glGenTextures(1, &texture_id);
    glActiveTexture(GL_TEXTURE0);           //see Create2D
    glBindTexture(GL_TEXTURE_2D, texture_id);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexStorage2D(GL_TEXTURE_2D, 1, GL_RGB16F, width, height);
    glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, width, height, GL_RGB, GL_FLOAT, hdr_data);
#else
    glCreateTextures(GL_TEXTURE_2D, 1, &texture_id);
    glTextureParameteri(texture_id, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTextureParameteri(texture_id, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTextureParameteri(texture_id, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTextureParameteri(texture_id, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTextureStorage2D(texture_id, 1, GL_RGB16F, width, height);
    glTextureSubImage2D(texture_id, 0, 0, 0, width, height, GL_RGB, GL_FLOAT, hdr_data);
#endif
}

// Bilinear-filtered HDR sample. x, y in [0, 1].
vec3 Texture::GetValueAtF(float x, float y){
    x = clamp(x, 0.0f, 1.0f);
    y = clamp(y, 0.0f, 1.0f);

    float px = x * (width  - 1);
    float py = y * (height - 1);
    int x0 = (int)px,  y0 = (int)py;
    int x1 = min(x0 + 1, width  - 1);
    int y1 = min(y0 + 1, height - 1);
    float fx = px - x0,  fy = py - y0;

    auto s = [&](int cx, int cy) -> vec3 {
        int i = (cy * width + cx) * 3;
        return vec3(hdr_data[i], hdr_data[i+1], hdr_data[i+2]);
    };
    return s(x0,y0).lerp(s(x1,y0), fx).lerp(
           s(x0,y1).lerp(s(x1,y1), fx), fy);
}

void Texture::AppendTexture(Texture* target, int2 at){
    debug->Info("Adding texture of size (%i x %i) at texture (%i,%i)\n",target->width,target->height, at.x,at.y);
    //At would provide the top left of where you want to put it.
    int new_image_width  = max(at.x + target->width,width);
    int new_image_height = max(at.y + target->height,height);

    if (IsEmpty()){
        //Just take in the image format
        image_format = target->image_format;
        storage_format = target->storage_format;
    }

    int num_channels = (image_format == GL_RGB) ? 3 : 4;
    size_t new_image_data_sz = new_image_width * new_image_height * num_channels;

    debug->Info("New image size = %i x %i: sz: %zu\n",new_image_width, new_image_height, new_image_data_sz);
    uint8_t* new_img_data = (uint8_t*)malloc(new_image_data_sz);

    uint8_t* write_ptr = new_img_data;
    uint8_t* first_data = img_data;
    uint8_t* second_data = target->img_data;
    int num_lines = new_image_height;

    int current_line_length = width;
    int line_length_inc = new_image_width - width;

    uint8_t* empty_line = (uint8_t*)calloc(new_image_width * num_channels,1);

    //Now we scan the old image into the new image first:
    for (int l=0;l<num_lines;l++){
        //debug->Info("Copy 1st Line %i Linewidth = %i\n",l,width);
        CopyLine(first_data,width,write_ptr,num_channels);
        write_ptr   += width * num_channels;
        first_data  += width * num_channels;

        //Add empty line
        CopyLine(empty_line,line_length_inc,write_ptr,num_channels);
        write_ptr   += line_length_inc * num_channels;
    }

    //Then we overwrite with the new image.
    //Scan the line from at.y to at.y + target->height
    for (int l=at.y;l<at.y+target->height;l++){
        write_ptr = new_img_data;
        write_ptr += l * new_image_width * num_channels; //start of current line

        //Increment pointer with x offset
        write_ptr   += at.x * num_channels;

        CopyLine(second_data,target->width,write_ptr,num_channels);
        second_data += target->width * num_channels;
        write_ptr   += target->width * num_channels;

        int remain = new_image_width - target->width - at.x;

        //Perhaps we fill this line with some more emptyness?
        CopyLine(empty_line,remain,write_ptr,num_channels);
    }

    //Finalise
    width = new_image_width;
    height = new_image_height;
    //Image format should already match or be set.
    //Free any existing data. file_data is only let go of, never freed: it belongs to the file
    //layer, which lent it to us and keeps it (File.h).
    free(img_data);
    img_data = NULL;
    file_data = NULL;
    file_data_sz = 0;
    free(empty_line);
    img_data = new_img_data;
    img_data_sz = new_image_data_sz;
}


/*
    Loads an image and hands its pixels to `rrand` to draw from - one decode feeding both the GPU
    and the simulation.

    This direction of the dependency is the point. RRandom used to hold a Texture*, which made
    core/RRandom.h include glad.h, so asking for a seeded integer pulled in the whole OpenGL
    loader - and a rules layer (tetris/Playfield.h, breakout/Field.h) could not include it at all.
    Both wrote their own copy of the same xorshift32 instead. Now Texture knows about RRandom and
    RRandom knows nothing about textures, files or GL.

    The bytes stay THIS texture's: RRandom::UseNoise does not copy them and will never free them,
    so this Texture must outlive every generator pointed at it. Several generators may share one
    noise texture - each keeps its own cursor, and its seed picks where in the buffer it starts.

    `depth_in` is passed straight through, so TEXTURE_DONT_UPLOAD gives CPU-side noise with no GL
    object at all - which is what a caller wanting this only for the simulation should pass.

    Note the buffer handed over is the DECODED image, so it is width*height*channels bytes, not
    one byte per pixel. That is not a problem for noise - every byte is as random as every other -
    but it does mean RRandom::GetSquareSide() describes the buffer rather than this image; the
    real dimensions are this object's own width and height.
*/
void Texture::LoadIntoRRandomNoiseFile(const char* filename, int target, int depth_in, RRandom* rrand){
    LoadFromFile(filename,target,depth_in);
    if (!rrand){
        return;
    }
    if (!img_data || (img_data_sz == 0)){
        //LoadFromFile has already said which file and why. Saying it again as a generator problem
        //is what stops this looking like "the random numbers are broken" later on.
        debug->Err("LoadIntoRRandomNoiseFile: %s yielded no pixels, generator left empty\n",filename);
        return;
    }
    rrand->UseNoise(img_data,img_data_sz);
}