#ifndef _UI_SHEET_H_
#define _UI_SHEET_H_

#include <string>
#include <vector>

#include "type_vec2.h"

/*
    A packed sprite sheet and the theme that gives its sprites meaning.

    TWO FILES, AND THE SPLIT IS THE WHOLE POINT.

    The SHEET (uisheet.json) is GENERATED by whatever packer produced the atlas. It says where each
    sprite sits and nothing else, because that is all a packer can know. It is rewritten in full
    every time the art is repacked, so nothing may ever be hand-edited into it - anything added
    there is lost on the next export, silently, and the loss looks like a bug in the code.

    The THEME (theme.json) is HAND-AUTHORED and says what the sprites mean: which one is the
    window frame, where its nine-slice cuts fall, which one a button is drawn from. None of that is
    derivable from a packed atlas, and all of it has to survive a repack.

    So the sheet is addressed BY NAME and the names are the contract. Positions churn with every
    pack and that is fine - that is what the sheet file is for - but a renamed input file changes a
    key and breaks the theme, which is why roles live in the theme rather than being parsed out of
    filename suffixes.

    --- WHAT THE PACKER'S FORMAT IS, AND WHY THIS READS TWO OF THEM -------------------------------
    The exporter has already changed shape once between two packs of the same art: the first was
    TexturePacker's JSON-Hash - a "frames" wrapper, `w`/`h`, `spriteSourceSize`, `trimmed`, and a
    `meta.image` naming the PNG - and the second was flat top-level keys with `width`/`height` and
    no `meta` at all. Both are accepted here, because a loader that only read one of them was
    already broken by a setting nobody remembered changing.

    NO `meta.image` MEANS THE SHEET NO LONGER NAMES ITS OWN PNG, so the caller supplies it. The
    convention is the same basename, and it is a convention rather than data.

    --- TRIMMING IS NOT SUPPORTED, ON PURPOSE ----------------------------------------------------
    A trimmed sprite is stored without its transparent margin and carries the offset to put it back
    (`spriteSourceSize`). That interacts badly with nine-slicing - the insets are measured against
    the UNtrimmed art, so trimming shifts every one of them - and the art here is packed untrimmed.
    LoadSheet refuses a trimmed frame rather than drawing it in the wrong place.
*/

//One sprite's rectangle in the atlas, in PIXELS. Top-left origin, matching both the packer's
//coordinates and UIOverlay's own screen space.
struct ui_sprite{
    std::string name;
    int x = 0;
    int y = 0;
    int w = 0;
    int h = 0;
};

/*
    How a themed element is drawn.

    `slice` is the nine-slice inset per side, in pixels of the source sprite. All zero means the
    sprite is drawn whole at whatever size is asked for, which is what a fixed sprite like a close
    button wants. Top and bottom zero with left and right set is a THREE-slice - the right answer
    for a button, whose height belongs to the artist and whose width stretches to its label.
*/
struct ui_element{
    std::string name;       //the role: "panel", "button", "close"
    std::string sprite;     //which sprite in the sheet draws it
    float slice_left = 0.0f;
    float slice_top = 0.0f;
    float slice_right = 0.0f;
    float slice_bottom = 0.0f;
};

class UISheet{
public:
    /*
        Reads the packer's JSON. `asset` is an asset name, resolved the usual way.

        Returns false and logs on a malformed file or a trimmed frame. A sheet that fails to load
        leaves the object empty rather than half-filled, so Find() simply misses and a caller draws
        nothing instead of drawing garbage from stale rectangles.
    */
    bool LoadSheet(const char* asset);

    //Reads the hand-authored theme. Same failure behaviour.
    bool LoadTheme(const char* asset);

    /*
        Checks every sprite fits inside an atlas of `w` x `h`, and logs the ones that do not.

        WORTH CALLING, because the JSON and the PNG are two separate assets with nothing tying them
        together - export one without the other and the sprites still "load", they just sample the
        wrong pixels. A frame that runs off the edge of the texture is the one symptom of that which
        can be caught for free.
    */
    bool ValidateAgainstAtlas(int w, int h) const;

    const ui_sprite*  FindSprite(const char* name) const;
    const ui_element* FindElement(const char* name) const;

    int GetNumSprites() const { return (int)sprites.size(); }
    int GetNumElements() const { return (int)elements.size(); }

private:
    std::vector<ui_sprite>  sprites;
    std::vector<ui_element> elements;
};

#endif
