#ifndef SHIP_COLLISION_MASKS_H
#define SHIP_COLLISION_MASKS_H

enum collision_category_bits{
    COLLISION_CATEGORY_ASTEROID = 0x0001,
    COLLISION_CATEGORY_SHIP = 0x0002,
    COLLISION_CATEGORY_LASER = 0x0004,
    COLLISION_CATEGORY_DOOR = 0x0008,
    COLLISION_CATEGORY_PICKUP = 0x0010
};
#endif